server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: rental
          uri: http://localhost:8082
          predicates:
            - Path=/rentals/**, 
        - id: book
          uri: http://localhost:8083
          predicates:
            - Path=/books/**, 
        - id: member
          uri: http://localhost:8084
          predicates:
            - Path=/members/**, 
        - id: view
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rentals/**, 
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: view
          uri: http://view:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
